services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: bash -c "bundle check || bundle install && rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle/gems
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=development
      - RAILS_MAX_THREADS=5
      - BUNDLE_WITHOUT=
    depends_on:
      - redis
    stdin_open: true
    tty: true
    networks:
      - depot-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - depot-network
    command: redis-server --appendonly yes

volumes:
  bundle_cache:
  redis_data:

networks:
  depot-network:
    driver: bridge
